spring.application.name=restAPI_PJ

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.minimum-idle=3
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=600000
spring.datasource.hikari.data-source-properties.profileSQL=true

mybatis.type-aliases-package=com.ssafy.trip.model.dto

mybatis.mapper-locations=classpath:/mappers/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true


ssafy.jwt.access-expmin= 100
ssafy.jwt.refresh-expmin= 100

logging.level.org.springframework.security=DEBUG

# 서비스 키
# 사용할 OpenAI chat model의 이름
spring.ai.openai.chat.options.model=gpt-4o-mini
# 창의성을 제어하는데 사용되는 샘플링 온도: 높을 수록 창의성이 높아짐 - 뻘소리할 확율도.. (0~2)
spring.ai.openai.chat.options.temperature=0.7
# 출력과 추론에 사용되는 토큰 수의 상한선
spring.ai.openai.chat.options.maxCompletionTokens=10000


# redis 서버 URL
# schema 초기화 여부
spring.ai.vectorstore.redis.initialize-schema=false
# 인덱스 이름
spring.ai.vectorstore.redis.index=ssafy-index
# 접두사
spring.ai.vectorstore.redis.prefix=ssafy:
# system prompt
ssafy.ai.system-prompt=You are an artificial intelligence known as an omniscient scholar. When you speak, use {language} and answer with a {character} personality.
ssafy.ai.rag-prompt=Context information is below, surrounded by ---------------------\
\
---------------------\
{question_answer_context}\
---------------------\
\
Given the context and provided history information, reply to the user comment based strictly on the information in the context.\
If the answer is not found in the context, inform the user: "I don't have specific information about this in my knowledge base" and then you may provide a general response based on your training. \
Otherwise, provide a comprehensive answer using only the information from the context. \
